stages:
    - check
    - build
    - test

variables:
    BUILD_TYPE: Release
    GIT_SUBMODULE_STRATEGY: recursive

image: gitlab-registry.cern.ch/acts/machines/slc6:latest

before_script:
    # CI executor uses fail on error by default
    # setup scripts do not like that
    - set +e && source CI/setup_lcg92.sh; set -e

format:
  stage: check
  variables:
    GIT_SUBMODULE_STRATEGY: none # we don't need to check core submodule
  image: gitlab-registry.cern.ch/acts/machines/check:latest
  before_script: []
  script:
    - CI/check_format .
  artifacts:
    paths:
      - changed
    when: on_failure

license:
  stage: check
  image: python:alpine3.6
  variables:
    GIT_SUBMODULE_STRATEGY: none # we don't need to check core submodule
  before_script: []
  script:
    - CI/check_license.py .

versions:
  stage: check
  variables:
    GIT_SUBMODULE_STRATEGY: none # we don't need to check core submodule
  tags:
    - cvmfs
  script:
    - ./CI/show_versions.sh

build:
  stage: build
  tags:
    - cvmfs
  script:
    - mkdir build
    - cd build
    - cmake -GNinja -DUSE_DD4HEP=on -DUSE_GEANT4=on -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
    - cmake --build . -- install
  artifacts:
    paths:
      - install

hello_world:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - ACTFWHelloWorldExample

generic_extrapolation:
  stage: test
  tags:
    - cvmfs
  script:
    - source install_default/bin/setup.sh
    - ACTFWGenericExtrapolationExample

reproducibility_generic_extrapolation:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - cd scripts
    - ./testReproducibility.sh GenericExtrapolation excells_charged
