stages:
    - check
    - build
    - test

variables:
    BUILD_TYPE: Release
    GIT_SUBMODULE_STRATEGY: recursive

image: gitlab-registry.cern.ch/acts/machines/slc6:latest

before_script:
    # CI executor uses fail on error by default
    # setup scripts do not like that
    - set +e && source CI/setup_lcg92.sh; set -e

format:
  stage: check
  variables:
    GIT_SUBMODULE_STRATEGY: none # we don't need to check core submodule
  image: gitlab-registry.cern.ch/acts/machines/check:latest
  before_script: 
    - git submodule deinit -f external/*
  script:
    - CI/check_format .
  artifacts:
    paths:
      - changed
    when: on_failure

license:
  stage: check
  image: python:alpine3.6
  variables:
    GIT_SUBMODULE_STRATEGY: none # we don't need to check core submodule
  before_script:
    - apk --no-cache add git
    - git submodule deinit -f external/*
  script:
    - CI/check_license.py .

versions:
  stage: check
  variables:
    GIT_SUBMODULE_STRATEGY: none # we don't need to check core submodule
  tags:
    - cvmfs
  script:
    - ./CI/show_versions.sh

build:
  stage: build
  tags:
    - cvmfs
  script:
    - mkdir build
    - cd build
    - cmake -GNinja -DUSE_FATRAS=on -DUSE_TGEO=on -DUSE_DD4HEP=on -DUSE_GEANT4=on -DUSE_PYTHIA8=on -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
    - cmake --build . -- install
  artifacts:
    paths:
      - install

build_vanilla:
  stage: build
  tags:
    - cvmfs
  script:
    - mkdir build
    - cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
    - cmake --build . -- install

hello_world:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - ACTFWHelloWorldExample

generic_propagation:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - ACTFWGenericPropagationExample

bfieldaccess_example:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - ACTFWBFieldAccessExample

generic_extrapolation_example:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - ACTFWGenericExtrapolationExample

particle_gun_example:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - ACTFWParticleGunExample

whiteboard_example:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - ACTFWWhiteBoardExample

bfield_example:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - ACTFWBFieldExample

generic_geometry_example:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - ACTFWGenericGeometryExample

random_number_example:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - ACTFWRandomNumberExample

reproducibility_generic_propagation:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/bin/setup.sh
    - cd scripts
    - ./testReproducibility.sh GenericPropagation 10 propagation-steps
